language: node_js
node_js:
  - "0.10"
  - "0.11"
before_install:
  - echo "_auth = $NPM_API_TOKEN" > $HOME/.npmrc
  - echo "registry = $NPM_REGISTRY" >> $HOME/.npmrc
  - echo "email = $NPM_EMAIL" >> $HOME/.npmrc
  - echo "always-auth = true" >> $HOME/.npmrc
env:
  global:
    - NPM_EMAIL="incubation@bandwidth.com"
    - NPM_REGISTRY="https://npm.bwrnd.com"
    # NPM_API_TOKEN
    - secure: "Gkgsb6+5PSORyNRkKMHExf3mgVC06ZcU8L8hsrmZTVmFhe/ELcNTbl5IUDPimSMK6EZHyucZO8t3MB7j/PaG/DUj5jkGC7xObrjZUvs+T/5rCaMzkIfW0kRXc3WqIB+xXbYD6sdqFL7l3fOkv41rMR1V80xX6axWA2MiD27v0AU="
