language: node_js
node_js:
  - "0.10"
  - "0.11"
before_install:
  - echo "_auth = $NPM_API_TOKEN}" > $HOME/.npmrc
  - echo "registry = $NPM_REGISTRY}" >> $HOME/.npmrc
  - echo "email = $NPM_EMAIL}" >> $HOME/.npmrc
  - echo "always-auth = true" >> $HOME/.npmrc
env:
  global:
    - NPM_EMAIL="incubation@bandwidth.com"
    - NPM_REGISTRY="https://npm.bwrnd.com"
    # NPM_API_TOKEN
    - secure: "k76r+Vt28+M+4nTGPYBx5wYyMelmBFyOnFim2TgvECgLIuUDScSvVToiamuz48VulcKLnZhCpLSmduk0qxHngG8dJez+EgQZNkHnj2GODU84lVkShy5H7IqYGK2t/USgKtYeKO4F6aqlG+LIv/FajYV90Ivuy9ZaH9jT9lRiuKs="
